# Generated by Django 5.1.6 on 2025-02-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='descricao',
            field=models.CharField(max_length=600),
        ),
    ]
